---
name: Manual + Push Workflow

on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Hello ${{ inputs.name }}"
          else
            echo "Hello from push event!"
          fi
